name: Upload Python Package

on:
    release:
        types: [published]

env:
    PYTHON-VERSION: 3.12
    WAIT-TIME: 1800 # 30 minutes in seconds
    CHECK-INTERVAL: 120 # 2 minutes in seconds
    ELAPSED-TIME: 0
    IMAGE: "ghcr.io/fairmat-nfdi/nomad-north-voila"
jobs:
    check-if-image-exists:
        name: Check image in GitHub Container Registry
        runs-on: ubuntu-latest
        steps:
            - name: Check if image exists in GitHub Container Registry
              run: |
                  FULL_IMAGE="${{ env.IMAGE }}:${GITHUB_REF_NAME}"
                  echo "Checking for the image ${FULL_IMAGE} to be available..."

                  while true; do
                    if docker manifest inspect ${FULL_IMAGE} > /dev/null 2>&1; then
                      echo "Image ${FULL_IMAGE} found successfully!"
                      exit 0
                    fi

                    if [[ ${{ env.ELAPSED-TIME }} -ge ${{ env.WAIT-TIME }} ]]; then
                      echo "Timeout reached (${{ env.WAIT-TIME }} seconds). Image ${FULL_IMAGE} not found!"
                      exit 1
                    fi

                    echo "Image not found yet. Retrying in ${{ env.CHECK-INTERVAL }} seconds... (${{ env.ELAPSED-TIME }}s / ${{ env.WAIT-TIME }}s elapsed)"
                    sleep ${{ env.CHECK-INTERVAL }}
                    ELAPSED_TIME=$((ELAPSED_TIME + ${{ env.CHECK-INTERVAL }}))
                  done

    build:
        name: Build Package
        runs-on: ubuntu-latest
        needs: check-if-image-exists
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  submodules: recursive
            - name: Install uv and set the Python version to ${{ env.PYTHON-VERSION }}
              uses: astral-sh/setup-uv@v5
              with:
                  python-version: ${{ env.PYTHON-VERSION }}

            - name: Overwrite the image tag
              run: |
                  IMAGE_TAG=$(grep -oP "${{ env.IMAGE }}:\K[^'\",]+" src/nomad_north_voila/north_tools/voila/__init__.py)

                  sed -i "s|${{ env.IMAGE }}:${IMAGE_TAG}|${{ env.IMAGE }}:${GITHUB_REF_NAME}|g" \
                  src/nomad_north_voila/north_tools/voila/__init__.py

            - name: Check image tag and build package
              run: |
                  IMAGE_TAG=$(grep -oP "${{ env.IMAGE }}:\K[^'\",]+" src/nomad_north_voila/north_tools/voila/__init__.py)

                  if [[ "${IMAGE_TAG}" == "${GITHUB_REF_NAME}" ]]; then
                    echo "Before building the Python package, image ${{ env.IMAGE }}:${GITHUB_REF_NAME} is updated for NORTH tool."
                  else
                    echo "Error: Image tag in __init__.py is not correct: ${IMAGE_TAG}. Expected: ${{ env.IMAGE }}:${GITHUB_REF_NAME}"
                    exit 1
                  fi

                  # Use SETUPTOOLS_SCM_PRETEND_VERSION to skip the version check due to image_tag modification of the __init__.py file
                  SETUPTOOLS_SCM_PRETEND_VERSION=${GITHUB_REF_NAME#v} uv build

            - name: Upload dist artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: dist-artifacts
                  path: dist/
            - name: Publish package distributions to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1

    deploy:
        name: Upload to PyPI
        needs: build
        runs-on: ubuntu-latest
        environment:
            name: pypi
            url: https://pypi.org/p/nomad-north-voila
        permissions:
            id-token: write
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  submodules: recursive
            - name: Download dist artifacts
              uses: actions/download-artifact@v4
              with:
                  name: dist-artifacts
                  path: dist/
            - name: Publish package distributions to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
